CREATE DATABASE LOP
USE LOP

CREATE TABLE TENLOP
(
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	MALOP VARCHAR(5) NOT NULL,
	TENLOP VARCHAR(20) NOT NULL,
)

INSERT INTO TENLOP VALUES ('L1', 'Lop mot');
INSERT INTO TENLOP VALUES ('L2', 'Lop hai');
INSERT INTO TENLOP VALUES ('L3', 'Lop ba');
INSERT INTO TENLOP VALUES ('L4', 'Lop bon');
INSERT INTO TENLOP VALUES ('L5', 'Lop nam');
INSERT INTO TENLOP VALUES ('L6', 'Lop sau');